[package]
name = "pistoncore-winit_window"
version = "0.7.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]
keywords = ["winit", "window", "piston"]
description = "A winit back-end for pistoncore-window"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/pistondevelopers/winit_window.git"
homepage = "https://github.com/pistondevelopers/winit_window"

[lib]
name = "winit_window"
path = "src/lib.rs"

[dependencies]
winit = "0.7"
vulkano = "0.7"
vulkano-win = "0.7"
pistoncore-input = "0.20.0"
pistoncore-window = "0.31.0"
